// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ghost

#pragma once

#include <vicarl/vicarl_export.h> // generated by CMake (GenerateExportHeader)

#ifdef __cplusplus
extern "C" {
#endif

typedef enum vicarl_status {
    VICARL_OK = 0,

    // Caller errors
    VICARL_ERR_INVALID_ARGUMENT = 1,

    // Data / format errors
    VICARL_ERR_FORMAT           = 2,
    VICARL_ERR_NOT_FOUND        = 3,

    // System / runtime errors
    VICARL_ERR_IO               = 4,
    VICARL_ERR_OOM              = 5,
    VICARL_ERR_BUSY             = 6,
    VICARL_ERR_UNSUPPORTED      = 7,

    // Crypto / verification
    VICARL_ERR_CRYPTO           = 8,

    // Library bug / unexpected state
    VICARL_ERR_INTERNAL         = 9
} vicarl_status_t;

/*
 * Returns a human-readable message describing the last error on the calling thread.
 *
 * Notes:
 *  - The returned pointer remains valid until the next vicarl_* call on the SAME thread.
 *  - On success-only paths, it may return an empty string.
 */
VICARL_EXPORT const char* vicarl_last_error_message(void);

/*
 * Frees memory returned by Vicarl APIs (vicarl_bytes_t buffers, strings, etc.).
 * Always use this rather than free()/delete, especially across shared library boundaries.
 */
VICARL_EXPORT void vicarl_free(void* p);

/*
 * Optional helper: convert status code to a stable string constant.
 * This is useful for logging and bindings.
 */
VICARL_EXPORT const char* vicarl_status_string(vicarl_status_t status);

/* Convenience macro */
#define VICARL_FAILED(s) ((s) != VICARL_OK)

#ifdef __cplusplus
}
#endif
