// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ghost

#pragma once

#include <stddef.h>
#include <stdint.h>

#include <vicarl/types.h>
#include <vicarl/error.h>
#include <vicarl/ledger.h>
#include <vicarl/store.h>
#include <vicarl/vicarl_ffi_export.h> // generated by CMake (GenerateExportHeader)

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle for FFI consumers.
typedef struct vicarl_ffi_ledger vicarl_ffi_ledger_t;

// Open a ledger. If opt is NULL, vicarl_ledger_open applies its defaults.
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_open(
    vicarl_ffi_ledger_t** out,
    const char* path,
    const vicarl_ledger_options_t* opt
);

VICARL_FFI_EXPORT void vicarl_ffi_ledger_close(vicarl_ffi_ledger_t* h);

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_append_record(
    vicarl_ffi_ledger_t* h,
    const uint8_t* record_bytes,
    size_t record_len,
    vicarl_hash32_t* out_record_id
);

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_flush(vicarl_ffi_ledger_t* h);

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_verify(vicarl_ffi_ledger_t* h);

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_tip(
    vicarl_ffi_ledger_t* h,
    uint64_t* out_segment_no,
    vicarl_hash32_t* out_segment_hash
);

// out_encoded_segment is allocated by the library; free via vicarl_ffi_free().
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_read_segment(
    vicarl_ffi_ledger_t* h,
    uint64_t segment_no,
    vicarl_bytes_t* out_encoded_segment
);

VICARL_FFI_EXPORT vicarl_store_kind_t vicarl_ffi_ledger_store_kind(vicarl_ffi_ledger_t* h);

// Thread-local last error message; valid until the next FFI call on the same thread.
VICARL_FFI_EXPORT const char* vicarl_ffi_last_error_message(void);

// Free memory allocated by FFI functions.
VICARL_FFI_EXPORT void vicarl_ffi_free(void* p);

#ifdef __cplusplus
}
#endif
