// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ghost

#pragma once

#include <stddef.h>
#include <stdint.h>

#include <vicarl/types.h>
#include <vicarl/error.h>
#include <vicarl/vicarl_ffi_export.h> // generated by CMake (GenerateExportHeader)

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle for FFI consumers.
typedef void* vicarl_handle_t;

/*
 * Open a ledger using default options.
 *
 * - Uses LOG store by default (simple) unless your implementation decides otherwise.
 * - For more configuration, FFI can grow into explicit open options later.
 */
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_open(vicarl_handle_t* out, const char* path);

/*
 * Close and free handle.
 */
VICARL_FFI_EXPORT void vicarl_ffi_close(vicarl_handle_t h);

/*
 * Append a canonical encoded record.
 */
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_append_record(vicarl_handle_t h, const uint8_t* rec, size_t rec_len, vicarl_hash32_t* out_record_id);

/*
 * Flush buffered records into a committed segment.
 */
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_flush(vicarl_handle_t h);

/*
 * Verify the ledger chain.
 */
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_verify(vicarl_handle_t h);

/*
 * Read a segment by number. Returns owned bytes in out_segment (free via vicarl_ffi_free()).
 */
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_read_segment(vicarl_handle_t h, uint64_t segment_no, vicarl_bytes_t* out_segment);

/*
 * Return last error message (thread-local).
 */
VICARL_FFI_EXPORT const char* vicarl_ffi_last_error_message(void);

/*
 * Free memory returned by FFI functions (mirrors vicarl_free).
 */
VICARL_FFI_EXPORT void vicarl_ffi_free(void* p);

#ifdef __cplusplus
}
#endif
