// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ghost

#include <vicarl/ledger.h>
#include <vicarl/store.h>
#include <vicarl/error.h>
#include <vicarl/types.h>

// Generated by generate_export_header(vicarl_ffi ...)
#include <vicarl/vicarl_ffi_export.h>

#include "../core/alloc_internal.h"
#include "../core/error_internal.h"

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle type for FFI consumers.
typedef struct vicarl_ffi_ledger {
    vicarl_ledger_t* ledger;
} vicarl_ffi_ledger_t;

/* Utility */

VICARL_FFI_EXPORT const char* vicarl_ffi_last_error(void) {
    return vicarl_last_error_message();
}

VICARL_FFI_EXPORT void vicarl_ffi_free(void* p) {
    vicarl_free(p);
}

/* Ledger lifecycle */

// Open a ledger. If opt==NULL, vicarl_ledger_open() applies defaults (via ledger.c).
VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_open(
    vicarl_ffi_ledger_t** out,
    const char* path,
    const vicarl_ledger_options_t* opt
) {
    if (!out) {
        vicarl__set_error_static("ffi_ledger_open: out is NULL");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    *out = NULL;

    if (!path || path[0] == '\0') {
        vicarl__set_error_static("ffi_ledger_open: path is empty");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    vicarl_ledger_t* led = NULL;
    vicarl_status_t st = vicarl_ledger_open(&led, path, opt);

    if (st != VICARL_OK) return st;

    vicarl_ffi_ledger_t* h = (vicarl_ffi_ledger_t*)vicarl__calloc(1, sizeof(vicarl_ffi_ledger_t));

    if (!h) {
        vicarl_ledger_close(led);
        vicarl__set_error_static("out of memory");

        return VICARL_ERR_OOM;
    }

    h->ledger = led;
    *out = h;

    return VICARL_OK;
}

VICARL_FFI_EXPORT void vicarl_ffi_ledger_close(vicarl_ffi_ledger_t* h) {
    if (!h) return;

    if (h->ledger) {
        vicarl_ledger_close(h->ledger);
        h->ledger = NULL;
    }

    vicarl__free(h);
}

/* Ledger operations */

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_append_record(
    vicarl_ffi_ledger_t* h,
    const uint8_t* record_bytes,
    size_t record_len,
    vicarl_hash32_t* out_record_id
) {
    if (!h || !h->ledger) {
        vicarl__set_error_static("ffi_ledger_append_record: invalid handle");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    if (!out_record_id) {
        vicarl__set_error_static("ffi_ledger_append_record: out_record_id is NULL");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    if (record_len > 0 && !record_bytes) {
        vicarl__set_error_static("ffi_ledger_append_record: record_bytes is NULL");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    return vicarl_ledger_append_record(
        h->ledger,
        (vicarl_slice_t){ .ptr = record_bytes, .len = record_len },
        out_record_id
    );
}

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_flush(vicarl_ffi_ledger_t* h) {
    if (!h || !h->ledger) {
        vicarl__set_error_static("ffi_ledger_flush: invalid handle");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    return vicarl_ledger_flush(h->ledger);
}

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_verify(vicarl_ffi_ledger_t* h) {
    if (!h || !h->ledger) {
        vicarl__set_error_static("ffi_ledger_verify: invalid handle");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    return vicarl_ledger_verify(h->ledger);
}

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_tip(
    vicarl_ffi_ledger_t* h,
    uint64_t* out_segment_no,
    vicarl_hash32_t* out_segment_hash
) {
    if (!h || !h->ledger) {
        vicarl__set_error_static("ffi_ledger_tip: invalid handle");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    return vicarl_ledger_tip(h->ledger, out_segment_no, out_segment_hash);
}

VICARL_FFI_EXPORT vicarl_status_t vicarl_ffi_ledger_read_segment(
    vicarl_ffi_ledger_t* h,
    uint64_t segment_no,
    vicarl_bytes_t* out_encoded_segment
) {
    if (!h || !h->ledger) {
        vicarl__set_error_static("ffi_ledger_read_segment: invalid handle");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    if (!out_encoded_segment) {
        vicarl__set_error_static("ffi_ledger_read_segment: out_encoded_segment is NULL");

        return VICARL_ERR_INVALID_ARGUMENT;
    }

    return vicarl_ledger_read_segment(h->ledger, segment_no, out_encoded_segment);
}

/* Optional convenience: expose underlying store kind */
VICARL_FFI_EXPORT vicarl_store_kind_t vicarl_ffi_ledger_store_kind(vicarl_ffi_ledger_t* h) {
    if (!h || !h->ledger) return 0;

    vicarl_store_t* s = vicarl_ledger_store(h->ledger);

    return vicarl_store_kind(s);
}

#ifdef __cplusplus
} // extern "C"
#endif
